import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BasicLayout from "./rootLayourt";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextCourse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BasicLayout children={children} params={""} />
      </body>
    </html>
  );
}
